services:
  - type: web
    name: services-marketplace
    env: python
    buildCommand: "pip install -r requirements.txt && cd backend && python manage.py collectstatic --noinput --clear && python manage.py migrate --noinput"
    startCommand: "cd backend && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "${RENDER_EXTERNAL_HOSTNAME},localhost,127.0.0.1"
      - key: IS_BEHIND_PROXY
        value: "True"
      - key: USE_TLS
        value: "True"
      - key: SECURE_SSL_REDIRECT
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: services-marketplace-db
          property: connectionString
    autoDeploy: true

  - type: postgresql
    name: services-marketplace-db
    plan: free

