services:
  - type: web
    name: services-marketplace
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd service_market_uz && gunicorn config.wsgi:application --workers 2 --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: marketplace-db
          property: connectionString
      - key: IS_BEHIND_PROXY
        value: True
      - key: USE_TLS
        value: True
      - key: PYTHON_VERSION
        value: 3.12.0

databases:
  - name: marketplace-db
    databaseName: marketplace
    user: marketplace_user
